apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journal
  template:
    metadata:
      labels:
        app: journal
    spec:
      containers:
        - name: journal-container
          image: harrylb/journal_web:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: journal-secrets

      volumes:
        - name: postgres





---

apiVersion: v1
kind: Service
metadata:
  name: journal-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    journal: web
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
