# Generated by Django 3.1.7 on 2021-02-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='framework',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='language',
            field=models.CharField(default='language', max_length=50),
            preserve_default=False,
        ),
    ]
