# Generated by Django 3.1.7 on 2021-03-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entries', '0002_auto_20210225_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Languages',
        ),
    ]
