# Generated by Django 3.1.7 on 2021-03-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entries', '0004_auto_20210301_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frameworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('resources', models.ManyToManyField(to='journal_entries.Resource')),
            ],
        ),
    ]
