# Generated by Django 3.1.7 on 2021-03-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entries', '0005_frameworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='framework',
            field=models.CharField(max_length=50, verbose_name='Frameworks/Technologies'),
        ),
    ]
