# Generated by Django 3.1.7 on 2021-03-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entries', '0006_auto_20210301_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='resource',
            name='framework',
            field=models.CharField(max_length=1000, verbose_name='Frameworks/Technologies'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='language',
            field=models.CharField(max_length=1000),
        ),
    ]
