# Generated by Django 3.1.7 on 2021-03-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entries', '0007_auto_20210301_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameworks',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='framework',
        ),
        migrations.AddField(
            model_name='resource',
            name='framework',
            field=models.ManyToManyField(to='journal_entries.Frameworks', verbose_name='Frameworks/Technologies'),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='language',
        ),
        migrations.AddField(
            model_name='resource',
            name='language',
            field=models.ManyToManyField(to='journal_entries.Languages'),
        ),
    ]
