# Generated by Django 3.1.7 on 2021-03-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entries', '0008_auto_20210302_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='framework',
            new_name='frameworks',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='language',
            new_name='languages',
        ),
    ]
