# Generated by Django 3.1.7 on 2021-03-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entries', '0009_auto_20210302_1125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frameworks',
            new_name='Framework',
        ),
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
    ]
