# Generated by Django 3.1.7 on 2021-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entries', '0010_auto_20210302_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='frameworks',
            field=models.ManyToManyField(to='journal_entries.Framework'),
        ),
    ]
